### ISSUE TITLE
Unify memory operations

### ISSUE THREAD

**Issue by mlund** [MEGA65/mega65-libc#22]
The commit [87ae766](https://github.com/MEGA65/mega65-libc/commit/87ae766a4458dc9d54daa570ac6b6bcb04a3ae0e) introduced new peek/poke functions in cc65. Ideally these should be available also in KickC and Clang. Related to #18.
Ping @ki-bo.

**Comment by mlund** [comment]
Are `lpeek` and `dma_peek` the same operation implemented in assembler and C, respectively on cc64?

**Comment by ki-bo** [comment]
@mlund They have the same effect, but dma_poke uses a DMA transfer to write a single byte. This is inefficient. The new lpoke uses 32 bit write operations to do the same in an efficient way.
