### ISSUE TITLE
Clarity of -1 return for `unsigned char` functions

### ISSUE THREAD

**Issue by mlund** [MEGA65/mega65-libc#37]
I assume all bits set is an error value. This corresponds a bit to `EOF` which is used by some C library functions for error result.
Typically such cases use `int` in as the return type. This may be less ideal on an 8-bit CPU when given the choice of return type.
Personally I think it is ugly to return -1 when the return type is unsigned. One can use `~0` or `~0u`, or perhaps better a macro to represent it.
Another way is to use `int8_t` as the return type which would signal that one can test for error by testing if the result is less than 0. In such case a negative value does not look inappropriate, which it kind of does now.

_Originally posted by @hth313 in https://github.com/MEGA65/mega65-libc/pull/29#discussion_r1267575969_

**Comment by mlund** [comment]
Thanks, how about `#define SDCARD_ERROR = UINT8_MAX`

**Comment by hth313** [comment]
That is fine to me (without the `=` in the actual code).

**Comment by mlund** [comment]
Ping @hth313: Hi Håkan, I pushed some changes that fixes this, please see #38.
