### ISSUE TITLE
setrtc/getrtc - investigate behaviour with r4/r5 RTC

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-libc#50]
The new RTCs on the r4 and r5 boards seem to behave differently. onboarding does setrtc/getrtc in short sequence which seems to give back old time. The new RTC lists a set buffer timeout of 950ms. Waiting long enough does work, but perhaps there is a different solution to this, that could be backed into libc.

**Comment by mlund** [comment]
@lydon42 can this be closed?
