### ISSUE TITLE
Problem with cinput 

### ISSUE THREAD

**Issue by giovannipozzobon** [MEGA65/mega65-libc#65]
I’m using the libc65 library with Calypsis. A very simple program that requires input from the user.

```
#include <stdio.h>
#include "debug_calypis.h"
#include "mega65/conio.h"
 
 unsigned char stringa[13];

void main (){
conioinit();

// Clear screen and go to the first position
clrscr();
gotoxy(0,0);

cinput(stringa, 13, CINPUT_ACCEPT_ALPHA);

}

```
The program freezes and monitor is starting.

I investigated and solved the problem by adding this control 
**`if (len ==0) return;`**

I hypothesize that the lcopy function messes up when the string length is zero, at least with the Calypsis compiler. I don't know with others.
If the length is greater than zero there is no problem.

```
void cputsxy(unsigned char x, unsigned char y, const unsigned char* s)
{
    const unsigned char len = (unsigned char)my_strlen((const char*)s);
    if (len ==0) return;
    const unsigned int offset = (y * (unsigned int)g_curScreenW) + x;
    lcopy((unsigned long)s, SCREEN_RAM_BASE + offset, len);
    lfill(COLOR_RAM_BASE + offset, g_curTextColor, len);
    g_curY = y + ((x + len) / g_curScreenW);
    g_curX = (x + len) % g_curScreenW;
}

```
The problem is that at MEGA65 hardware level at least, len=0 means 64Kbyte. This explains the problem.
<img width="709" alt="Screenshot 2024-09-08 alle 20 33 28" src="https://github.com/user-attachments/assets/b86bf7b3-b57a-45ae-9e0a-a0ecfe36bb0f">

**Comment by mlund** [comment]
I did a quick test with llvm-mos and the problem seem to exist there as well. `lcopy()` uses DMA copy via the F018 list structure where `count` number of bytes is defined. Could you try to test `lcopy()` separately to verify that it does nothing when length is zero?

If `lcopy()` is OK there, I see two routes:


1. Submit a PR for `cputsxy()` with the suggested range check, _or_
2. Do nothing but add a comment to `cputsxy()` that the string must be non-zero. On restricted systems like ours, this might be the best option(?)

**Comment by mlund** [comment]
Pushed ab8d78764045db1721af0519380a575e3af2335d that modifies documentation.

**Comment by giovannipozzobon** [comment]
I vote for the first choice because inside the c_input function there is this code that put '\0' in the buffer.
```
    for (i = 0; i < buflen; ++i) {
        buffer[i] = '\0';
    } 
```

**Comment by mlund** [comment]
OK, how about placing the range check just before calling `cputsxy()`, i.e. at line 735 of `cinput()`. It is less invasive and wouldn't impose checks on known non-zero strings.

**Comment by giovannipozzobon** [comment]
Do you mean like something that?
```
        if (strlen(buffer) != 0)  
            cputsxy(sx, sy, buffer);
```
Ok for me.

**Comment by lydon42** [comment]
> ```
>         if (strlen(buffer) != 0)  
>             cputsxy(sx, sy, buffer);
> ```

I don't think that is the right solution. you should be able to use cputsxy with an empty string. It should take care to not needlessly call lcopy on the empty string instead.

**Comment by mlund** [comment]
> Do you mean like something that?
> 
> ```
>         if (strlen(buffer) != 0)  
>             cputsxy(sx, sy, buffer);
> ```
> 
> Ok for me.

Yes, exactly. Would you mind making a pull request?

**Comment by giovannipozzobon** [comment]
> > Do you mean like something that?
> > ```
> >         if (strlen(buffer) != 0)  
> >             cputsxy(sx, sy, buffer);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ok for me.
> 
> Yes, exactly. Would you mind making a pull request?

OK. Done.
Thanks.
